name: Release
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: |
          npm ci
      - name: Release
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release